Repository brain-link/scanhub, pull requests merged in 2024-01, with the labels that each got.

#83 Use ruff linter for static testing
  .github/workflows/static-tests.yml
  services/acquisition-control/app/api/acquisitioncontrol.py
  services/acquisition-control/app/main.py
  services/acquisition-control/poetry.lock
  services/acquisition-control/pyproject.toml
  services/device-manager/app/api/dal.py
  services/device-manager/app/api/devices.py
  services/device-manager/app/api/models.py
  services/device-manager/app/main.py
  services/device-manager/poetry.lock
  services/device-manager/pyproject.toml
  services/exam-manager/app/api/dal.py
  services/exam-manager/app/main.py
  services/exam-manager/poetry.lock
  services/exam-manager/pyproject.toml
  services/mri/recos/cartesian-reco-service/app/api/reco.py
  services/mri/recos/cartesian-reco-service/app/main.py
  services/mri/recos/cartesian-reco-service/poetry.lock
  services/mri/recos/cartesian-reco-service/pyproject.toml
  services/mri/sequence-manager/app/database/mongodb.py
  services/mri/sequence-manager/app/dependencies.py
  services/mri/sequence-manager/app/endpoints/health.py
  services/mri/sequence-manager/app/endpoints/mri_sequence_endpoints.py
  services/mri/sequence-manager/app/main.py
  services/mri/sequence-manager/app/services/mri_sequence_service.py
  services/mri/sequence-manager/poetry.lock
  services/mri/sequence-manager/pyproject.toml
  services/mri/sequence-manager/tests/__init__.py
  services/mri/sequence-manager/tests/conftest.py
  services/mri/sequence-manager/tests/test_endpoints.py
  services/mri/sequence-manager/tests/test_mri_sequence_endpoints.py
  services/workflow-manager/app/api/producer.py
  services/workflow-manager/app/main.py
  services/workflow-manager/poetry.lock
  services/workflow-manager/pyproject.toml
Labels: priority: medium, type: testing

#86 Remove procedure and use UUID in exam manager
  .github/workflows/static-tests.yml
  services/exam-manager/app/api/dal.py
  services/exam-manager/app/api/db.py
  services/exam-manager/app/api/exam.py
  services/exam-manager/app/api/models.py
Labels: priority: medium

#89 HOTFIX: Build action fails
  .github/workflows/build.yml
  docker-compose.yml
Labels: type: bug, priority: critical
